name: 'Subset report'
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/ontology/uberon-edit.obo'
  workflow_dispatch:
env:
  STATUS: 1
jobs:
  is_changed:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:latest
    steps:
      # Checks-out current branch
      - uses: actions/checkout@v2
      # Checks-out main and prepare git diff report
      - name: create git diff
        id: gitdiff
        if: ${{ github.event.pull_request.base.sha }}
        run: |
          git fetch origin main ${{ github.event.pull_request.base.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > gitdiff.md
          cat gitdiff.md
          echo ::set-output name=diff::$(cat gitdiff.md)
      # Set Status to 0 to cancel the workflow' if keyword not in the diff file
      - name: conditional cancel
        if: "!contains(steps.gitdiff.outputs.diff, 'never_in_taxon')"
        run: |
          echo Taxon constraint updates do not exist
          echo "STATUS=0" >> $GITHUB_ENV
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        if: env.STATUS == 1
        with:
          ref: main
          path: main
      - name: make step for branch
        if: env.STATUS == 1
        run: echo branch
        #run: cd src/ontology && mkdir -p tmp reports mirror && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx20G' BRI=false MIR=false PAT=false IMP=false subsets/human-view.owl > TESTLOG.log
      - name: debugging branch
        if: ${{ failure() }}
        run: tail -20 src/ontology/TESTLOG.log
      - name: make step for main
        if: env.STATUS == 1
        run: echo branch
        #run: cd main/src/ontology && mkdir -p tmp reports mirror && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx20G' BRI=false MIR=false PAT=false IMP=false subsets/human-view.owl > TESTLOG.log
      - name: debugging main
        if: ${{ failure() }}
        run: tail -20 main/src/ontology/TESTLOG.log
      - name: prepare diff report
        if: env.STATUS == 2
        run: robot diff --left src/ontology/subsets/human-view.owl --right main/src/ontology/subsets/human-view.owl -f markdown -o report.md
      - name: prepare comment
        if: env.STATUS == 2
        run: |
          pwd
          ls
          "echo \"<details>\n <summary> Here's a diff of your *-view </summary> \n\" > view-comment.md; cat report.md >> view-comment.md"
      - name: post comment
        if: env.STATUS == 2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../view-comment.md"
      - name: shell scripting
        run: |
          pwd
          ls
